# Generated by Django 5.0.6 on 2024-05-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coba', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'permissions': [('can_test', 'just test description')]},
        ),
    ]
