# Generated by Django 5.0.6 on 2024-05-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coba', '0002_alter_test_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
