# Generated by Django 5.0.6 on 2024-06-18 13:17

import uploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uploader.models.Files.generate_id, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
