# Generated by Django 5.0.6 on 2024-06-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_files_created_at_files_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='path',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='files',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='url',
            field=models.TextField(default=None),
        ),
    ]
