# Generated by Django 5.0.6 on 2024-06-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_rename_deleted_files_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='full_url',
            field=models.TextField(default=None),
        ),
    ]
