# Generated by Django 5.0.6 on 2024-05-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('man_user', '0001_initial'),
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='MyUser',
        ),
    ]
