# Generated by Django 5.0.6 on 2024-05-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kong_jwt_token',
            name='man_user_ko_token_247411_idx',
        ),
    ]
