# Generated by Django 5.0.6 on 2024-05-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man_user', '0002_remove_kong_jwt_token_man_user_ko_token_247411_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kong_jwt_token',
            index=models.Index(fields=['token'], name='man_user_ko_token_247411_idx'),
        ),
    ]
