# Generated by Django 5.0.6 on 2024-05-19 07:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man_user', '0003_kongjwt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KongJWT',
            new_name='Kong_JWT',
        ),
    ]
