# Generated by Django 5.0.6 on 2024-05-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man_user', '0003_kong_jwt_token_man_user_ko_token_247411_idx'),
        ('man_user', '0004_alter_user'),
    ]

    operations = [
    ]
