# Generated by Django 5.0.6 on 2024-05-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man_user', '0004_rename_kongjwt_kong_jwt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kong_jwt',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='kong_jwt',
            name='deleted_by_cascade',
        ),
    ]
