# Generated by Django 5.0.6 on 2024-05-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man_user', '0006_user_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_proxy',
            name='uuid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
