# Generated by Django 5.0.6 on 2024-05-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man_user', '0006_kong_jwt_deleted_at_kong_jwt_deleted_by_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kong_JWT_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('kong_jwt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='man_user.kong_jwt')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
