# Generated by Django 5.0.6 on 2024-05-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man_user', '0007_kong_jwt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kong_jwt_token',
            name='kong_jwt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='man_user.kong_jwt'),
        ),
    ]
