version: '1'
services:
  minpro-db-management-user-container:
    container_name: minpro-db-management-user-container
    image: mysql:8.4
    restart: on-failure
    volumes:
      - type: volume
        source: minpro-db-management-user-volume
        target: /var/lib/mysql
        read_only: false
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_NATIVE_PASSWORD: ON
    ports:
      - "${DB_PORT}:3306"
    networks:
      - minpro-db-management-user-network
    # command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}", "-e", "SELECT 1"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 5s

volumes:
  minpro-db-management-user-volume:
   name: minpro-db-management-user-volume

networks:
  minpro-db-management-user-network:
    name: minpro-db-management-user-network
    driver: bridge
