version: '1'
services:
  minpro-db-management-user-container:
    container_name: minpro-db-management-user-container
    image: mysql:8.4
    restart: on-failure
    volumes:
      - type: volume
        source: minpro-db-management-user-volume
        target: /var/lib/mysql
        read_only: false
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_NATIVE_PASSWORD: ON
    ports:
      - "${DB_PORT}:3306"
    networks:
      - minpro-db-management-user-network
    # command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}", "-e", "SELECT 1"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 5s
  # minpro-kong:
  #   container_name: minpro-kong
  #   image: kong/kong-gateway:3.6.1.4
  #   ports:
  #     - "8000:8000"
  #     - "8443:8443"
  #     - "8001:8001"
  #     - "8444:8444"
  #     - "8002:8002"
  #     - "8445:8445"
  #     - "8003:8003"
  #     - "8004:8004"
  #   networks:
  #     - kong-net
  #   environment:
  #     - "KONG_PG_HOST=kong-database"
  #     - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
  #     - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
  #     - "KONG_PROXY_ERROR_LOG=/dev/stderr"
  #     - "KONG_DATABASE=postgres"
  #     - "KONG_PG_USER=kong"
  #     - "KONG_PG_PASSWORD=kongpass"
  #     - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
  #     - "KONG_ADMIN_LISTEN=0.0.0.0:8001,0.0.0.0:8444 ssl"
  #     - "KONG_ADMIN_GUI_URL=http://localhost:8002"
  #     - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  #     - "ASSET=ce"
  #     - "request_debug=on"
  #     - request_debug_token=1234

volumes:
  minpro-db-management-user-volume:
   name: minpro-db-management-user-volume

networks:
  minpro-db-management-user-network:
    name: minpro-db-management-user-network
    driver: bridge
  kong-net:
    name: kong-net
    driver: bridge
